# Generated by Django 3.0.8 on 2021-05-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_auto_20200912_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(upload_to='images/tours/'),
        ),
    ]
