# Generated by Django 3.0.8 on 2021-05-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_auto_20210512_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='publisher',
            field=models.CharField(default='', max_length=200),
        ),
    ]
