# Generated by Django 3.0.8 on 2021-05-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_tour_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='place',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_location',
        ),
        migrations.AddField(
            model_name='tour',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='tag',
            field=models.CharField(blank=True, help_text='tags', max_length=200, null=True),
        ),
    ]
