# Generated by Django 3.0.8 on 2021-05-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0028_auto_20210520_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tags',
            field=models.TextField(default='', max_length=200),
        ),
    ]
