# Generated by Django 3.0.8 on 2021-05-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0029_tour_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tags',
        ),
    ]
