# Generated by Django 3.0.8 on 2021-05-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0031_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(help_text='Description for images', max_length=30),
        ),
    ]
