# Generated by Django 3.0.8 on 2021-05-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0033_auto_20210520_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(help_text='tag of the game', max_length=20),
        ),
    ]
